:- use_module(library(pce)).


sendBox(Display, Ref, Color, X, Y) :-
    send(Display, display,
        new(Ref, box(100,100)), point(X*100, Y*100)),
            send(Ref, fill_pattern, Color).


start :-
    new(@Display, window('Chess', size(800,800))),
        sendBox(@Display, @a1, colour(white), 0, 0),
        sendBox(@Display, @a2, colour(orange), 0, 1),
        sendBox(@Display, @a3, colour(white), 0, 2),
        sendBox(@Display, @a4, colour(orange), 0, 3),
        sendBox(@Display, @a5, colour(white), 0, 4),
        sendBox(@Display, @a6, colour(orange), 0, 5),
        sendBox(@Display, @a7, colour(white), 0, 6),
        sendBox(@Display, @a8, colour(orange), 0, 7),
        sendBox(@Display, @b1, colour(orange), 1, 0),
        sendBox(@Display, @b2, colour(white), 1, 1),
        sendBox(@Display, @b3, colour(orange), 1, 2),
        sendBox(@Display, @b4, colour(white), 1, 3),
        sendBox(@Display, @b5, colour(orange), 1, 4),
        sendBox(@Display, @b6, colour(white), 1, 5),
        sendBox(@Display, @b7, colour(orange), 1, 6),
        sendBox(@Display, @b8, colour(white), 1, 7),
        sendBox(@Display, @c1, colour(white), 2, 0),
        sendBox(@Display, @c2, colour(orange), 2, 1),
        sendBox(@Display, @c3, colour(white), 2, 2),
        sendBox(@Display, @c4, colour(orange), 2, 3),
        sendBox(@Display, @c5, colour(white), 2, 4),
        sendBox(@Display, @c6, colour(orange), 2, 5),
        sendBox(@Display, @c7, colour(white), 2, 6),
        sendBox(@Display, @c8, colour(orange), 2, 7),
        sendBox(@Display, @d1, colour(orange), 3, 0),
        sendBox(@Display, @d2, colour(white), 3, 1),
        sendBox(@Display, @d3, colour(orange), 3, 2),
        sendBox(@Display, @d4, colour(white), 3, 3),
        sendBox(@Display, @d5, colour(orange), 3, 4),
        sendBox(@Display, @d6, colour(white), 3, 5),
        sendBox(@Display, @d7, colour(orange), 3, 6),
        sendBox(@Display, @d8, colour(white), 3, 7),
        sendBox(@Display, @e1, colour(white), 4, 0),
        sendBox(@Display, @e2, colour(orange), 4, 1),
        sendBox(@Display, @e3, colour(white), 4, 2),
        sendBox(@Display, @e4, colour(orange), 4, 3),
        sendBox(@Display, @e5, colour(white), 4, 4),
        sendBox(@Display, @e6, colour(orange), 4, 5),
        sendBox(@Display, @e7, colour(white), 4, 6),
        sendBox(@Display, @e8, colour(orange), 4, 7),
        sendBox(@Display, @f1, colour(orange), 5, 0),
        sendBox(@Display, @f2, colour(white), 5, 1),
        sendBox(@Display, @f3, colour(orange), 5, 2),
        sendBox(@Display, @f4, colour(white), 5, 3),
        sendBox(@Display, @f5, colour(orange), 5, 4),
        sendBox(@Display, @f6, colour(white), 5, 5),
        sendBox(@Display, @f7, colour(orange), 5, 6),
        sendBox(@Display, @f8, colour(white), 5, 7),
        sendBox(@Display, @g1, colour(white), 6, 0),
        sendBox(@Display, @g2, colour(orange), 6, 1),
        sendBox(@Display, @g3, colour(white), 6, 2),
        sendBox(@Display, @g4, colour(orange), 6, 3),
        sendBox(@Display, @g5, colour(white), 6, 4),
        sendBox(@Display, @g6, colour(orange), 6, 5),
        sendBox(@Display, @g7, colour(white), 6, 6),
        sendBox(@Display, @g8, colour(orange), 6, 7),
        sendBox(@Display, @h1, colour(orange), 7, 0),
        sendBox(@Display, @h2, colour(white), 7, 1),
        sendBox(@Display, @h3, colour(orange), 7, 2),
        sendBox(@Display, @h4, colour(white), 7, 3),
        sendBox(@Display, @h5, colour(orange), 7, 4),
        sendBox(@Display, @h6, colour(white), 7, 5),
        sendBox(@Display, @h7, colour(orange), 7, 6),
        sendBox(@Display, @h8, colour(white), 7, 7),
        send(@Display, open).